### ISSUE TITLE
Can't read the graphic card temperature.

### ISSUE THREAD

**Issue by EricESM** [haiyang1992/Hackintosh-Opencore-Asrock_Z390_Phantom_Gaming_ITX#1]
Hi, I have the exact hardware setup as your hardware.
got SMCxxxxxx.kext and VirtualSMC.kext
but still not working. 
do you have any recommendations?

Graphic card: 5700 xt

![Screen Shot 2020-09-23 at 1 14 09 AM](https://user-images.githubusercontent.com/10945713/93985580-20e48880-fd3a-11ea-9a0c-1d84ba927250.png)

**Comment by haiyang1992** [comment]
Are you using iStat menus? I think there's an incompatibility between VirtualSMC and iStat, which hides the GPU temps.

**Comment by EricESM** [comment]
> Are you using iStat menus? I think there's an incompatibility between VirtualSMC and iStat, which hides the GPU temps.

I am not using iStat menus.

**Comment by haiyang1992** [comment]
Yeah this could be a VirtualSMC problem.

**Comment by EricESM** [comment]
> Yeah this could be a VirtualSMC problem.

<img width="364" alt="Screen Shot 2020-09-24 at 7 19 42 PM" src="https://user-images.githubusercontent.com/10945713/94219128-ed6d3f80-fe9a-11ea-9de5-b9ab3883a54a.png">
somehow the tempture is working. but it shows 0 degree
